version: '3.8'

services:
  ibm-mq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: ibm-mq
    restart: always
    ports:
      - "1414:1414"                   # Porta para conexões MQ
      - "9443:9443"                   # Porta para o console web
    environment:
      LICENSE: accept                 # Aceita a licença do IBM MQ
      MQ_QMGR_NAME: QM1
      MQ_ENABLE_METRICS: "false"
      MQ_APP_PASSWORD: passw0rd          # Senha para o usuário 'app'
      MQ_ADMIN_PASSWORD: passw0rd
    volumes:
      - mq-data:/var/mqm              # Volume para persistir os dados do MQ

volumes:
  mq-data:
    driver: local